spring:
  application:
    name: zapquest
  profiles:
    active: dev
  output:
    ansi:
      enabled: always

# Initialize the database using data.sql
# jpa:
#   defer-datasource-initialization: true
# sql:
#   init:
#     mode: always
